plugins {
    id "com.android.application"
}

android {
    namespace "com.evil.manualcodex"
    compileSdk 35

    defaultConfig {
        applicationId "com.manualcodex.imported_com_devil_winnerstudio"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}


dependencies {
    implementation "com.rmtheis:tess-two:9.1.0"
    implementation "com.google.mlkit:text-recognition:16.0.1"
}
